<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="GridView.aspx.cs" Inherits="OnlineWebApplication.WebApplication.GridView" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Content_Body" runat="server">
    
    
         <asp:GridView ID="GridView1" ShowHeaderWhenEmpty="true" DataKeyNames="MobileID" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" EmptyDataText="No Records Found" runat ="server" AutoGenerateColumns="false" ShowFooter="true" AllowPaging="true"  OnPageIndexChanging="OnPageIndexChanging" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
                 OnRowEditing="GridView1_RowEditing" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowUpdating="GridView1_RowUpdating" OnRowDeleting="GridView1_RowDeleting">  
       <Columns>
                <asp:TemplateField HeaderText="MobileID">
                    <EditItemTemplate>
                         <asp:TextBox ID="txtMobileID" runat="server" Text='<%# Bind("MobileID") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblUserId" runat="server" Text='<%# Bind("MobileID")%>'>
                        </asp:Label>
                    </ItemTemplate>
                     <FooterTemplate>
                        <asp:LinkButton ID ="btnInsert" Text ="Insert" runat ="server" OnClick ="btnInsert_Click" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Brand">
                    <EditItemTemplate>
                         <asp:TextBox ID="txtBrand" runat="server" Text='<%# Bind("Brand") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblBrand" runat="server" Text='<%# Bind("Brand")%>'>
                        </asp:Label>
                     </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtBrandFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Model">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtModel" runat="server" Text='<%# Bind("Model") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblModel" runat="server" Text='<%# Bind("Model")%>'>
                        </asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtModelFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                  <asp:TemplateField HeaderText="Battery">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtBattery" runat="server" Text='<%# Bind("Battery") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblBattery" runat="server" Text='<%# Bind("Battery")%>'>
                        </asp:Label>
                    </ItemTemplate>
                        <FooterTemplate>
                        <asp:TextBox ID="txtBatteryFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                 <asp:TemplateField HeaderText="RAM">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtRAM" runat="server" Text='<%# Bind("RAM") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblRAM" runat="server" Text='<%# Bind("RAM")%>'>
                        </asp:Label>
                    </ItemTemplate>
                      <FooterTemplate>
                        <asp:TextBox ID="txtRAMFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="ROM">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtROM" runat="server" Text='<%# Bind("ROM") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblROM" runat="server" Text='<%# Bind("ROM")%>'>
                        </asp:Label>
                    </ItemTemplate>
                        <FooterTemplate>
                        <asp:TextBox ID="txtROMFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Price">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtPrice" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblPrice" runat="server" Text='<%# Bind("Price")%>'>
                        </asp:Label>
                    </ItemTemplate>
                        <FooterTemplate>
                        <asp:TextBox ID="txtPriceFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
            </asp:GridView>
</asp:Content>
