<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="GridView.aspx.cs" Inherits="OnlineWebApplication.WebApplication.GridView" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Content_Body" runat="server">
    <tr>

    </tr>
    <td>
        <asp:GridView ID="Gv_OnlineMobileShop" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" Datakeynames="userId" ShowFooter="true"
                         OnRowCancelingEdit=" Gv_OnlineMobileShop_RowCancelingEdit"  OnRowDeleting=" Gv_OnlineMobileShop_RowDeleting"  OnRowEditing=" Gv_OnlineMobileShop_RowEditing" OnRowUpdating=" Gv_OnlineMobileShop_RowUpdating" Height="147px" Width="540px">
            <Columns>
                <asp:TemplateField HeaderText="UserId">
                    <EditItemTemplate>
                         <asp:TextBox ID="txtUserId" runat="server" Text='<%# Bind("userId") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblUserId" runat="server" Text='<%# Bind("userId")%>'>
                        </asp:Label>
                    </ItemTemplate>
                     <FooterTemplate>
                        <asp:LinkButton ID ="btnInsert" Text ="Insert" runat ="server" OnClick ="btnInsert_Click" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name">
                    <EditItemTemplate>
                         <asp:TextBox ID="txtName" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblName" runat="server" Text='<%# Bind("name")%>'>
                        </asp:Label>
                     </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtNameFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Number">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtNumber" runat="server" Text='<%# Bind("number") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblNumber" runat="server" Text='<%# Bind("number")%>'>
                        </asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtNumberFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                  <asp:TemplateField HeaderText="MailId">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtMailId" runat="server" Text='<%# Bind("mailID") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblMailId" runat="server" Text='<%# Bind("mailID")%>'>
                        </asp:Label>
                    </ItemTemplate>
                        <FooterTemplate>
                        <asp:TextBox ID="txtMailIdFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                 <asp:TemplateField HeaderText="Password">
                     <EditItemTemplate>
                         <asp:TextBox ID="txtPassword" runat="server" Text='<%# Bind("password") %>'></asp:TextBox>  
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblPassword" runat="server" Text='<%# Bind("password")%>'>
                        </asp:Label>
                    </ItemTemplate>
                      <FooterTemplate>
                        <asp:TextBox ID="txtPasswordFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
            </asp:GridView>
    </td>
</asp:Content>
